### ISSUE TITLE
Interface parameter accepts macros only for strings, not for drop-down integers

### ISSUE THREAD

**Issue by mathieumd** [TheNetworkGuy/netbox-zabbix-sync#118]
In the section [Set interface parameters within NetBox](https://github.com/TheNetworkGuy/netbox-zabbix-sync?tab=readme-ov-file#set-interface-parameters-within-netbox) of the README, you say: *I would recommend using macros for sensitive data such as community strings since the data in NetBox is plain-text.*

Although it works for strings (`authpassphrase`, `privpassphrase` and `securityname`), it does not for drop-down menus (`authprotocol`, `privprotocol` and `securitylevel`; and `bulk` too, I guess):

```yaml
{
    "zabbix": {
        "interface_type": 2,
        "snmp": {
            "authpassphrase": "{$SNMPV3_AUTHPASS}",
            "authprotocol": "{$SNMPV3_AUTHPROTO}",
            "privpassphrase": "{$SNMPV3_PRIVPASS}",
            "privprotocol": "{$SNMPV3_PRIVPROTO}",
            "securitylevel": "{$SNMPV3_SECLEVEL}",
            "securityname": "{$SNMPV3_LOGIN}",
            "version": 3
        }
    }
}
```

NetBox-Zabbix-sync returns:

```
2025-04-08 15:06:58,132 - NetBox-Zabbix-sync - WARNING - Host EXAMPLE: Interface OUT of sync.
2025-04-08 15:06:58,144 - NetBox-Zabbix-sync - ERROR - Zabbix returned the following error: Invalid params. Incorrect arguments passed to function..
```

This config context is working:
```yaml
{
    "zabbix": {
        "interface_type": 2,
        "snmp": {
            "authpassphrase": "{$SNMPV3_AUTHPASS}",
            "authprotocol": 5,
            "privpassphrase": "{$SNMPV3_PRIVPASS}",
            "privprotocol": 5,
            "securitylevel": 2,
            "securityname": "{$SNMPV3_LOGIN}",
            "version": 3
        }
    }
}
```
